apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: staging

configMapGenerator:
  - name: nginx-html
    files:
      - index.html

generatorOptions:
  disableNameSuffixHash: false

