apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: prod

configMapGenerator:
  - name: nginx-html
    files:
      - index.html

generatorOptions:
  disableNameSuffixHash: false

patches:
  - path: service-ports-jsonpatch.yaml
    target:
      version: v1
      kind: Service
      name: nginx
